# Generated by Django 4.0.2 on 2022-03-01 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='owner',
            new_name='user',
        ),
    ]
